In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from IPython.display import display

In [2]:
iris = load_iris()
x = iris.data
feature_names = iris.feature_names
y = iris.target
df = pd.DataFrame(x, columns=feature_names)
display(df)
df["target"] = y
display(df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [3]:
rng = np.random.default_rng(32)
indices = np.arange(len(x))
print(indices)
PERCENTAGE = 0.70
print(indices.size)
SIZE = int(indices.size * PERCENTAGE)
train_indices = rng.choice(indices, size=SIZE, replace=False)
test_indices = np.setdiff1d(indices, train_indices)
print(train_indices)
print(test_indices)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149]
150
[ 69  15  51  76  14  39  53  19  49 121  85  30  74  18 136 129   0  21
  59 133 149 117  12 112  26  99  68 139 126 141 143  37 132 135 134 125
  62 119  81  58  93 114  64  29  60 123   5 144  20 103  56   6   9 147
 113  52  17  95  41 130  55  45   7  66  96  92  40 128  43  34  10   3
  36 111 109  50  35 104  42 106  57  86 107 116  47 138 110  73  32 105
  70 145 120  84  72  28 124  31  78 102  77  89 140  80  97]
[  1   2   4   8  11  13  16  22  23  24  25  27  33  38  44  46  48  54
  61  63  65  67  71  75  79  82  83  87  88  90  91  94  98 100 101 108
 115 118 122 127 131 137 142 146 148]

In [4]:
x_train = x[train_indices]
x_test = x[test_indices]
y_train = y[train_indices]
y_test = y[test_indices]

x_train_df = pd.DataFrame(x_train, columns=iris.feature_names)
x_test_df = pd.DataFrame(x_test, columns=iris.feature_names)

y_train_df = pd.DataFrame(y_train, columns=["target"])
y_test_df = pd.DataFrame(y_test, columns=["target"])
display(x_train_df.tail())
display(y_train_df.tail())
display(x_test_df.tail())
display(y_test_df.tail())

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
100                6.7               3.0                5.0               1.7
101                5.5               2.5                4.0               1.3
102                6.7               3.1                5.6               2.4
103                5.5               2.4                3.8               1.1
104                6.2               2.9                4.3               1.3

     target
100       1
101       1
102       2
103       1
104       1

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
40                7.9               3.8                6.4               2.0
41                6.4               3.1                5.5               1.8
42                5.8               2.7                5.1               1.9
43                6.3               2.5                5.0               1.9
44                6.2               3.4                5.4               2.3

    target
40       2
41       2
42       2
43       2
44       2